-------------------------------------------------------------------------------
Test set: LocationsTest
-------------------------------------------------------------------------------
Tests run: 3, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 5.348 sec <<< FAILURE! - in LocationsTest
createInstanceOfLocationsClass(LocationsTest)  Time elapsed: 0.64 sec  <<< ERROR!
org.sql2o.Sql2oException: 
Could not acquire a connection from DataSource - FATAL: no pg_hba.conf entry for host "197.237.130.216", user "
gqolqzxnoggkco", database "d7ahf3qn69ju0m", SSL off
Caused by: org.postgresql.util.PSQLException: 
FATAL: no pg_hba.conf entry for host "197.237.130.216", user "
gqolqzxnoggkco", database "d7ahf3qn69ju0m", SSL off

entryIsDeletedSuccessfully(LocationsTest)  Time elapsed: 1.681 sec  <<< ERROR!
org.sql2o.Sql2oException: 
Could not acquire a connection from DataSource - FATAL: no pg_hba.conf entry for host "197.237.130.216", user "
gqolqzxnoggkco", database "d7ahf3qn69ju0m", SSL off
Caused by: org.postgresql.util.PSQLException: 
FATAL: no pg_hba.conf entry for host "197.237.130.216", user "
gqolqzxnoggkco", database "d7ahf3qn69ju0m", SSL off

allEntriesAreSaved(LocationsTest)  Time elapsed: 3.026 sec  <<< ERROR!
org.sql2o.Sql2oException: 
Could not acquire a connection from DataSource - FATAL: no pg_hba.conf entry for host "197.237.130.216", user "
gqolqzxnoggkco", database "d7ahf3qn69ju0m", SSL off
Caused by: org.postgresql.util.PSQLException: 
FATAL: no pg_hba.conf entry for host "197.237.130.216", user "
gqolqzxnoggkco", database "d7ahf3qn69ju0m", SSL off

